[WARNING] ME(2329748:281473553582384,MainProcess):2025-09-02-14:00:38.620.2 [mindspore/run_check/_check_version.py:412] Can not find the tbe operator implementation(need by mindspore-ascend). Please check whether the Environment Variable PYTHONPATH is set. For details, refer to the installation guidelines: https://www.mindspore.cn/install
/home/ma-user/anaconda3/envs/MindSpore/lib/python3.9/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/ma-user/anaconda3/envs/MindSpore/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/ma-user/anaconda3/envs/MindSpore/lib/python3.9/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/ma-user/anaconda3/envs/MindSpore/lib/python3.9/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
[WARNING] ME(2329748:281473553582384,MainProcess):2025-09-02-14:00:42.621.647 [mindspore/run_check/_check_version.py:412] Can not find the tbe operator implementation(need by mindspore-ascend). Please check whether the Environment Variable PYTHONPATH is set. For details, refer to the installation guidelines: https://www.mindspore.cn/install
[WARNING] DISTRIBUTED(2329748,ffffab2cc930,python):2025-09-02-14:00:42.623.626 [mindspore/ccsrc/distributed/rpc/tcp/tcp_comm.cc:485] Connect] Connection 17 source: 127.0.0.1:58700, destination: 127.0.0.1:8118
[WARNING] DISTRIBUTED(2329748,ffffab2cc930,python):2025-09-02-14:00:42.623.684 [mindspore/ccsrc/distributed/rpc/tcp/tcp_client.cc:76] Connect] Failed to connect to the tcp server : 127.0.0.1:8118, retry to reconnect(1/1)...
[WARNING] DISTRIBUTED(2329748,ffffab2cc930,python):2025-09-02-14:00:43.123.771 [mindspore/ccsrc/distributed/cluster/topology/compute_graph_node.cc:173] Register] Failed to connect to the meta server node url: 127.0.0.1:8118
[WARNING] DISTRIBUTED(2329748,ffffab2cc930,python):2025-09-02-14:00:43.123.809 [mindspore/ccsrc/distributed/cluster/topology/compute_graph_node.cc:363] ReconnectWithTimeoutWindow] Failed to register and try to reconnect to the meta server.
[WARNING] DISTRIBUTED(2329748,ffffab2cc930,python):2025-09-02-14:00:43.624.016 [mindspore/ccsrc/distributed/rpc/tcp/tcp_comm.cc:485] Connect] Connection 18 source: 127.0.0.1:58728, destination: 127.0.0.1:8118
[WARNING] DISTRIBUTED(2329748,ffffab2cc930,python):2025-09-02-14:00:43.624.055 [mindspore/ccsrc/distributed/rpc/tcp/tcp_comm.cc:494] Connect] Waiting for the state of the connection to 127.0.0.1:8118 to be connected...Retry number: 1
[WARNING] DISTRIBUTED(2329748,ffff358c91e0,python):2025-09-02-14:00:43.624.056 [mindspore/ccsrc/distributed/rpc/tcp/tcp_comm.cc:79] ConnectedEventHandler] Connection from 127.0.0.1:58728 to 127.0.0.1:8118 is successfully created. System errno: Success
[WARNING] DISTRIBUTED(2329748,ffffab2cc930,python):2025-09-02-14:00:44.124.279 [mindspore/ccsrc/distributed/rpc/tcp/tcp_comm.cc:485] Connect] Connection 19 source: 127.0.0.1:53064, destination: 127.0.0.1:8118
[WARNING] DISTRIBUTED(2329748,ffffab2cc930,python):2025-09-02-14:00:44.124.319 [mindspore/ccsrc/distributed/rpc/tcp/tcp_comm.cc:494] Connect] Waiting for the state of the connection to 127.0.0.1:8118 to be connected...Retry number: 2
[WARNING] DISTRIBUTED(2329748,ffff348c71e0,python):2025-09-02-14:00:44.124.312 [mindspore/ccsrc/distributed/rpc/tcp/tcp_comm.cc:79] ConnectedEventHandler] Connection from 127.0.0.1:53064 to 127.0.0.1:8118 is successfully created. System errno: Success
[WARNING] DISTRIBUTED(2329748,ffffab2cc930,python):2025-09-02-14:00:44.625.361 [mindspore/ccsrc/distributed/cluster/cluster_context.cc:246] BuildCluster] Topology build timed out., retry(1/1200).
[WARNING] DISTRIBUTED(2329748,ffffab2cc930,python):2025-09-02-14:00:45.125.521 [mindspore/ccsrc/distributed/cluster/cluster_context.cc:249] BuildCluster] Cluster is successfully initialized.
[WARNING] DISTRIBUTED(2329748,ffffab2cc930,python):2025-09-02-14:00:45.125.712 [mindspore/ccsrc/distributed/cluster/cluster_context.cc:356] PostProcess] This node 1 rank id: 1
[WARNING] DISTRIBUTED(2329748,ffffab2cc930,python):2025-09-02-14:00:50.814.945 [mindspore/ccsrc/distributed/collective/collective_manager.cc:338] CreateCommunicationGroup] Start to create communication group: hccl_world_group [const vector]{0, 1, 2, 3, 4, 5, 6, 7}, async: 0, submit_now: 1
[WARNING] DISTRIBUTED(2329748,fffe9b7fe1e0,python):2025-09-02-14:00:50.815.439 [mindspore/ccsrc/distributed/collective/collective_manager.cc:962] CreateDeviceCommunicator] Begin initialize communication group on the device side: hccl_world_group
[WARNING] DEVICE(2329748,fffe9affd1e0,python):2025-09-02-14:00:50.815.632 [mindspore/ccsrc/plugin/res_manager/ascend/collective/ascend_communication_group.cc:165] InitializeByRankTable] Start to initialize communicator by HcclCommInitClusterInfoConfig for hccl_world_group, hcclBufferSize is 200 MB. hcclDeterministic is 0
[WARNING] DEVICE(2329748,fffe9affd1e0,python):2025-09-02-14:00:50.915.798 [mindspore/ccsrc/plugin/res_manager/ascend/collective/ascend_communication_group.cc:175] InitializeByRankTable] End to initialize communicator by HcclCommInitClusterInfoConfig for hccl_world_group
[WARNING] DISTRIBUTED(2329748,fffe9b7fe1e0,python):2025-09-02-14:00:50.916.180 [mindspore/ccsrc/distributed/collective/collective_manager.cc:973] CreateDeviceCommunicator] End initialize communication group on the device side: hccl_world_group
.Scanning 'coco/train2017.cache.npy' images and labels... 118287 found, 0 missing, 1021 empty, 0 corrupted: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 118287/118287 [00:00<?, ?it/s]Scanning 'coco/train2017.cache.npy' images and labels... 118287 found, 0 missing, 1021 empty, 0 corrupted: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 118287/118287 [00:00<?, ?it/s]
Scanning 'coco/train2017.cache.npy' images and labels... 118287 found, 0 missing, 1021 empty, 0 corrupted: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 118287/118287 [00:00<?, ?it/s]Scanning 'coco/train2017.cache.npy' images and labels... 118287 found, 0 missing, 1021 empty, 0 corrupted: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 118287/118287 [00:00<?, ?it/s]
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
[WARNING] package not installed, albumentations load failed
........